apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql-db
  template:
    metadata:
      labels:
        app: sql-db
    spec:
      containers:
      - name: sql-container
        image: mysql:5.7
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: "sql-db"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
