apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}-frontend
  labels:
    app: {{ include "myapp.name" . }}-frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}-frontend
    spec:
      containers:
        - name: fe-container
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          resources:
            requests:
              memory: "{{ .Values.frontend.resources.requests.memory }}"
              cpu: "{{ .Values.frontend.resources.requests.cpu }}"
            limits:
              memory: "{{ .Values.frontend.resources.limits.memory }}"
              cpu: "{{ .Values.frontend.resources.limits.cpu }}"
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
